nailit-elasticsearch:
  container_name: nailit-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/nailit/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
nailit-postgresql:
  container_name: nailit-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/nailit/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=nailit
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
